export const TASK_NAMES = {
  helloapi: "helloapi",
  moderation: "moderation",
  blogger: "blogger",
  liar: "liar",
  inprompt: "inprompt",
  embedding: "embedding",
  whisper: "whisper",
  functions: "functions",
  rodo: "rodo",
  scraper: "scraper",
  whoami: "whoami",
  search: "search",
  people: "people",
  knowledge: "knowledge",
  tools: "tools",
  gnome: "gnome",
  ownapi: "ownapi",
};

export const MODEL_NAMES = {
  gpt_4: "gpt-4-0613",
  gpt_4_turbo: "gpt-4-1106-preview",
  gpt_4_vision: "gpt-4-vision-preview",
  gpt_3_5_turbo: "gpt-3.5-turbo",
  gpt_3_5_turbo_1106: "gpt-3.5-turbo-1106",
  embeddings: "text-embedding-ada-002",
  whisper: "whisper-1",
  text_to_speech: "tts-1",
  text_to_speech_HD: "tts-1-hd",
  dall_e_3: "dall-e-3",
  dall_e_2: "dall-e-2",
};
